export const prompt_beginning = "Write a ";
export const prompt_style = [
    'rap',
    'song',
    'poem',
    'speech',
    'haiku',
    'sonnet',
    'statement',
    'prayer',
]
export const prompt_middle = "by ";
export const prompt_narrators = [
    'Sam Bankman Fried',
    'Barack Obama',
    'Taylor Swift',
    'Ariana Grande',
    'Justin Bieber',
    'Donald Trump',
    'Bill Clinton',
    'Elon Musk',
    'Kanye West',
    'Chris Rock',
    'Dave Chapelle',
    'Katy Perry',
    'Rihanna',
    'Narendra Modi',
    'Lady Gaga',
    'Selena Gomez',
    'Britney Spears',
    'Demi Lovato',
    'Drake',
    'Miley Cyrus',
    'Jimmmy Fallon',
    'Winston Churchill',
    'Bill Gates',
    'Abraham Lincoln',
    'Thomas Jefferson',
    'John F. Kennedy',
    'Aristotle',
    'George Washington',
    'Napoleon',
    'William Shakespeare',
    'Cleopatra',
    'Julius Caesar',
    'Alexander the Great',
    'a 14 year old girl with ADHD',
    'a 60 year old man who has lived through several financial bubbles',
    'a 87 year old Japanese man who runs a pizza shop',
    'a vegan crypto billionaire',
    'a 40 year old man who roleplays as a cat',
    'a professor from MIT',
    'a detective penguin',
    'a cat accountant',
    'a dog dentist',
    'a parrot pilot',
    'a proud squirrel doctor',
    'a turtle traffic cop',
];

export const prompt_end = [
    ' that compares not paying royalties on digital art to stubbing your toe.',
    ' that compares not paying royalties on digital art to tripping on a banana.',
    ' that compares not paying royalties on digital art to farting in an elevator.',
    ' that compares not paying royalties on digital art to eating the last cookie in the jar.',
    ' that compares not paying royalties on digital art to trying to eat a piece of cake without taking a bite.',
    ' that compares not paying royalties on digital art to trying to swim without getting wet.',
    ' that compares not paying royalties on digital art to trying to run a marathon without training.',
    ' that compares not paying royalties on digital art to trying to sneak into a movie theater without paying.',
    ' that compares not paying royalties on digital art to borrowing a friend\'s car without asking.',
    ' that compares not paying royalties on digital art to going to a restaurant and not tipping the waiter.',
    ' that compares not paying royalties on digital art to going to a concert and trying to sneak into the VIP section.',
    ' that compares not paying royalties on digital art to trying to shoplift from a grocery store.',
    ' that compares not paying royalties on digital art to trying to get a free gym membership by using someone else\'s ID.',
    ' that compares not paying royalties on digital art to trying to use a fake ID to buy alcohol',
    ' that compares not paying royalties on digital art to a penguin walking into a bar, ordering a martini, and proceeding to perform stand-up comedy for the astonished patrons.',
    ' that compares not paying royalties on digital art to a group of cows in a field starting a synchronized dance routine to the beat of "YMCA" blaring from a nearby radio.',
    ' that compares not paying royalties on digital art to a chicken wearing a tutu and ballet slippers performing a perfect pas de deux with a surprised farmer.',
    ' that compares not paying royalties on digital art to a cat, a dog, and a hamster teaming up to open a detective agency and solve the case of the missing toilet paper roll.',
    ' that compares not paying royalties on digital art to a group of geriatric dolphins escaping from a retirement home and head to the beach for a wild night of surfing and partying.',
    ' that compares not paying royalties on digital art to a group of chickens start a band and perform a rocking concert in the middle of a farm.',
    ' that scolds the users for not paying royalties on digital art like a caring grandma.',
    ' that compares not paying royalties on digital art to a sandwich that comes alive and wreaks havoc on their local neighborhood.',
    ' that compares not paying royalties on digital art to accidentally dropping your phone into a toilet.',
    ' that compares not paying royalties on digital art to cartwheeling away from an awkward social situation.',
    ' that compares not paying royalties on digital art to opening a stubborn jar of pickles.'
    ' that compares not paying royalties on digital art to doing a yoga pose but instead falling into a pile of laundry.',
    ' that compares not paying royalties on digital art to leverage longing on a Solana investment.',
    ' that compares not paying royalties on digital art to a reality TV show.',
    ' that compares not paying royalties on digital art to cooking a fancy meal for a date gone wrong.',
    ' that compares not paying royalties on digital art to a very romantic telenovela.',
    ' that compares not paying royalties on digital art to doing a magic trick but accidentally setting your own hair on fire.',
    ' that compares not paying royalties on digital art to losing weight.',
    ' that compares not paying royalties on digital art to taking ice baths',
    ' that compares not paying royalties on digital art to taking a cold shower.',
    ' that compares not paying royalties on digital art to breakdancing.',
    ' that compares not paying royalties on digital art to dirt biking.',
    ' that compares not paying royalties on digital art to being arrested by a law enforcement agency.',
    ' that compares not paying royalties on digital art to making a sandwich.',
    ' that compares not paying royalties on digital art to brushing teeth.',
    ' that compares not paying royalties on digital art to baking cookies with a pair of scissors.',
    ' that compares not paying royalties on digital art to playing Animal Crossing',
    ' that compares not paying royalties on digital art to an intense game of Starcraft',
    ' that compares not paying royalties on digital art to shitposting on Twitter',
]